// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxvCihe6wQ-6DFl-2nd18-vCgnJsP_QtE',
    appId: '1:795125594532:web:b04bf734b5508ca17fe931',
    messagingSenderId: '795125594532',
    projectId: 'chat-firebase-flutter-6688a',
    authDomain: 'chat-firebase-flutter-6688a.firebaseapp.com',
    storageBucket: 'chat-firebase-flutter-6688a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfMC4bA9maD1uTuKQ6mzp7BHYhQJ67qfw',
    appId: '1:795125594532:android:06e1c97926d26d5b7fe931',
    messagingSenderId: '795125594532',
    projectId: 'chat-firebase-flutter-6688a',
    storageBucket: 'chat-firebase-flutter-6688a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPjIY0OTLKiihcbclS2V09K9TJG0IZAmI',
    appId: '1:795125594532:ios:8a3787013e995df67fe931',
    messagingSenderId: '795125594532',
    projectId: 'chat-firebase-flutter-6688a',
    storageBucket: 'chat-firebase-flutter-6688a.appspot.com',
    androidClientId: '795125594532-lh77ruq8lqsdmaqvvrsg22pvj8p2m80i.apps.googleusercontent.com',
    iosClientId: '795125594532-97ol5b2qddhsuft601pcjmknu29vbno6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFlutterFirebase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPjIY0OTLKiihcbclS2V09K9TJG0IZAmI',
    appId: '1:795125594532:ios:8a3787013e995df67fe931',
    messagingSenderId: '795125594532',
    projectId: 'chat-firebase-flutter-6688a',
    storageBucket: 'chat-firebase-flutter-6688a.appspot.com',
    androidClientId: '795125594532-lh77ruq8lqsdmaqvvrsg22pvj8p2m80i.apps.googleusercontent.com',
    iosClientId: '795125594532-97ol5b2qddhsuft601pcjmknu29vbno6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFlutterFirebase2',
  );
}
